
services:
  backend:
    build: ./backend
    container_name: adif-backend
    ports:
      - "8080:8080"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  

